myapp/urls.py
from django.urls import path, include
from . import views

app_name = "myapp"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("post_create", views.PostCreate.as_view(), name="post_create"),
    path("post_detail/<int:pk>", views.PostDetail.as_view(), name="post_detail"),
    path("post_update/<int:pk>", views.PostUpdate.as_view(), name="post_update"),
    path("post_delete/<int:pk>", views.PostDelete.as_view(), name="post_delete"),
    path("post_list", views.PostList.as_view(), name="post_list"),
    path("login", views.Login.as_view(), name="login"),
    path("logout", views.Logout.as_view(), name="logout"),
    path("signup", views.SignUp.as_view(), name="signup"),
    path("like/<int:post_id>", views.Like_add, name="like_add"),
    path("category_list", views.CategoryList.as_view(), name="category_list"),
    path(
        "category_detail/<str:name_en>",
        views.CategoryDetail.as_view(),
        name="category_detail",
    ),
    path("search", views.Search, name="search"),
    path('guest_login/', views.guest_login, name = 'guest_login'), #ゲストログイン用
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

import numpy as np
import tensorflow as tf
import tensorflow.compat.v1 as tf1
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image
import io, base64



class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""
       
    class Meta:
        verbose_name_plural = 'CustomUser'


class Category(models.Model):
    name = models.CharField("カテゴリ名", max_length=50)
    name_en = models.CharField("カテゴリ名英語", max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey("CustomUser", on_delete=models.PROTECT, blank=False)
    title = models.CharField("タイトル", max_length=50)
    content = models.TextField("内容", max_length=1000)
    category = models.ForeignKey("Category", on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to="images/", blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.PROTECT)
    user = models.ForeignKey(CustomUser, verbose_name="Likeしたユーザー", on_delete=models.PROTECT)


graph = tf1.get_default_graph()


class Photo(models.Model):
    image = models.ImageField(upload_to='images/')

    IMAGE_SIZE = 224 # 画像サイズ
    MODEL_FILE_PATH = './classify/ml_models/vgg16_transfer.h5' # モデルファイル
    classes = ["2", "3", "4", "5", "6", "7", 
              "8", "9", "10", "11"]
    num_classes = len(classes)

    # 引数から画像ファイルを参照して読み込む
    def predict(self):
        model = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)
            
            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            return self.classes[predicted], percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

myapp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import CustomUser


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content", "category", "thumbnail")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class SearchForm(forms.Form):
    freeword = forms.CharField(min_length=1, max_length=30, label="", required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

myapp/views.py
from django.shortcuts import render, resolve_url, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import (
    TemplateView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
)
from .models import Post, Like, Category
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator

from .models import Photo
from .models import CustomUser



class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exceptions = True

    def test_func(self):
        post = Post.objects.get(id=self.kwargs["pk"])
        return post.author == self.request.user


class Index(TemplateView):
    template_name = "myapp/index.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by("-created_at")
        context = {
            "post_list": post_list,
        }
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy("myapp:index")

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        post = form.save(commit=False)
        if post.category_id == 1:
            photo = Photo(image=form.cleaned_data['thumbnail'])
            predicted, percentage = photo.predict()
            post.category_id = predicted

        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, "Postを登録しました。")
        return resolve_url("myapp:index")


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        detail_data = Post.objects.get(id=self.kwargs["pk"])
        category_posts = Post.objects.filter(category=detail_data.category).order_by(
            "-created_at"
        )[:5]
        params = {
            "object": detail_data,
            "category_posts": category_posts,
        }
        return params


class PostUpdate(OnlyMyPostMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        if post.category_id == 1:
            photo = Photo(image=form.cleaned_data['thumbnail'])
            predicted, percentage = photo.predict()
            post.category_id = predicted

        return super(PostUpdate, self).form_valid(form)

    def get_success_url(self):
        messages.info(self.request, "Postを更新しました。")
        return resolve_url("myapp:post_detail", pk=self.kwargs["pk"])
    

class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.info(self.request, "Postを削除しました。")
        return resolve_url("myapp:index")


class PostList(ListView):
    model = Post
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.all().order_by("-created_at")


class Login(LoginView):
    form_class = LoginForm
    template_name = "myapp/login.html"


class Logout(LogoutView):
    template_name = "myapp/logout.html"


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = "myapp/signup.html"
    success_url = reverse_lazy("myapp:index")

    def form_valid(self, form):
        user = form.save()

        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')

        self.object = user
        messages.info(self.request, "ユーザー登録をしました。")
        return HttpResponseRedirect(self.get_success_url())


@login_required
def Like_add(request, post_id):
    post = Post.objects.get(id=post_id)
    is_liked = Like.objects.filter(user=request.user, post=post_id).count()
    if is_liked > 0:
        messages.info(request, "すでにお気に入りに追加済みです。")
        return redirect("myapp:post_detail", post.id)
    like = Like()
    like.user = request.user
    like.post = post
    like.save()

    messages.success(request, "お気に入りに追加しました！")
    return redirect("myapp:post_detail", post.id)


class CategoryList(ListView):
    model = Category


class CategoryDetail(DetailView):
    model = Category
    slug_field = "name_en"
    slug_url_kwarg = "name_en"

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en=self.kwargs["name_en"])
        category_posts = Post.objects.filter(category=detail_data.id).order_by(
            "-created_at"
        )

        params = {
            "object": detail_data,
            "category_posts": category_posts,
        }

        return params


def Search(request):
    if request.method == "POST":
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data["freeword"]
            search_list = Post.objects.filter(
                Q(title__icontains=freeword) | Q(content__icontains=freeword)
            )

        params = {
            "search_list": search_list,
        }

        return render(request, "myapp/search.html", params)


def predict(request):

    form = PhotoForm(request.POST, request.FILES)

    photo = Photo(image=form.cleaned_data['image'])
    predicted, percentage = photo.predict()

    context = {
        'photo_name': photo.image.name,
        'photo_data': photo.image_src(),
        'predicted': predicted,
        'percentage': percentage,
    }

    return HttpResponse(template.render(context, request))


def guest_login(request):
    guest_user = CustomUser.objects.get(email='guest@guest.guest')
    login(request, guest_user, backend='django.contrib.auth.backends.ModelBackend')
    
    return redirect('myapp:index')
    

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <title>{{ request.site.siteconfig.meta_title }}</title>
        
        <!-- Font Awesome -->
        <link
        href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
        />
        <!-- Bootstrap core CSS -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css"
        rel="stylesheet"
        />
        <!-- Material Design Bootstrap -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css"
        rel="stylesheet"
        />
        
        <!-- Your custom styles (optional) -->
        <!-- <link rel="stylesheet" href="css/style.css" /> -->
    </head>
    
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="/">PHOTO CLASSIFY</a>
            
            <!-- Toggle button -->
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#basicExampleNav"
                aria-controls="basicExampleNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
                ></button>
            
            <!-- Collapsible wrapper -->
            <div class="tab-area">
                <ul id="tabmenu" class="nav nav-tabs tab-menu" role="tablist">
                    
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                        <a class="nav-link">{{ request.user }}</a>
                        {% endif %}
                    </li>
                    
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'myapp:logout' %}">ログアウト</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'myapp:login' %}">ログイン</a>
                        {% endif %}
                    </li>
                    
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                        {% else %}
                        <a class="nav-link" href="{% url 'myapp:guest_login' %}">ゲストユーザー<br>としてログイン</a>
                        {% endif %}
                    </li>
                    
                    <li class="nav-item">
                        {% if request.user.is_authenticated %}
                        {% else %}
                        <a class="nav-link" href="{% url 'myapp:signup' %}">ユーザー登録</a>
                        {% endif %}
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:post_create' %}">新規投稿</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:post_list' %}">投稿一覧</a>
                    </li>
                    
                </ul>
            </div>
            

                    
                </ul>
                <!-- links -->
                
                <!-- Search form -->
                <form action="{% url 'myapp:search' %}" class="form-inline" method="POST">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search", name="freeword">
                        </form>
            </div>
            <!-- Collapsible wrapper -->
        </nav>
        <!-- Navbar -->
        
        <main class="container">
            
            {% if messages %}
            　　　　<br>
            {% for message in messages %}
            
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            
            </ul>
            {% endif %}
            
            
            {% block content %} {% endblock %}</main>
        
        <!-- Start your project here-->
        
        <!-- Footer -->
        <footer class="bg-light text-center text-lg-start">
            <!-- Grid container -->
            <div class="container p-4">
                <!--Grid row-->
                <div class="row">
                    <!--Grid column-->
                    <div class="col-lg-6 col-md-12 mb-4 mb-md-0">

                    </div>
                    <!--Grid column-->
                    
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                        
                    </div>
                    <!--Grid column-->
                    
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                       
                    </div>
                    <!--Grid column-->
                </div>
                <!--Grid row-->
            </div>
            <!-- Grid container -->
            
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                <a class="text-dark" href="{% url 'myapp:index' %}">PHOTO CLASSIFY</a>
            </div>
            <!-- Copyright -->
        </footer>
        <!-- Footer -->
        
        <!-- SCRIPTS -->
        <!-- JQuery -->
        <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="js/popper.min.js"></script>
        <!-- JQuery -->
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <!-- JQuery -->
        <script type="text/javascript" src="js/mdb.min.js"></script>
    </body>
</html>

myapp/templates/myapp/category_detail.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-9">
    <br />
    <h2>{{ object.name }}</h2>
    <hr />
    <ul class="list-group">
      {% for item in category_posts %}
      <li class="list-group-item">
        <a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a>
      </li>
      {% endfor %}
    </ul>
    <br />
  </div>
</div>

{% endblock %}

myapp/templates/myapp/category_list.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-9">
    <br />
    <h2>Category List</h2>
    <br />
  </div>
</div>
<div class="row">
  {% for category in category_list %}
  <div class="col-md-4">
    <br />
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'myapp:category_detail' category.name_en %}">{{ category.name }}</a>
<!--            <small>{{ category.post_count }}</small>-->
        </h4>
        <hr />
        {% for post in category.post_set.all|slice:":5" %}
        <p><a href="{% url 'myapp:post_detail' post.id %}" style="color: black">{{ post.title }}</a></p>
        {% endfor %}
        <br />
        <a href="{% url 'myapp:category_detail' category.name_en %}">このカテゴリの記事を全て見る</a>
      </div>
    </div>
  </div>

  {% endfor %}
</div>
<br />

{% endblock %}

myapp/templates/myapp/guest_login.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-6">
    <br />
    <h2>Login</h2>
    <br />

    <form action="" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
        {{field.label }}
        {{ field }}
        {{ field.errors }}
        <br />
      {% endfor %}

      <button type="submit" class="btn btn-primary">Login</button>
      <br />
      <br />
    </form>
  </div>
</div>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %} {% block content %}
<!-- Start your project here-->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="display-4">PHOTO CLASSIFY</h2>
    <p class="lead">AIでジャンル分けする写真投稿サイト</p>
  </div>
</div>

<div class="row">

  <!-- Card deck -->
  <div class="card-deck">
    {% for item in post_list %}
    <div class="col-md-4">
      <!-- Card -->
      <div class="card mb-4">
        <!-- Card image -->
        <div class="view overlay">
          {% if item.thumbnail %}
          <img
            class="card-img-top"
            src="{{ item.thumbnail.url }}"
            alt="{{item.title}}"
          />
          {% else %}
          <img
            class="card-img-top"
            src="https://mdbootstrap.com/img/new/standard/city/041.jpg"
            alt="{{item.title}}"
          />
          {% endif %}
          <a href="{% url 'myapp:post_detail' item.id %}">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <div class="card-body">
          <h4 class="card-title">
            {{ item.title }}
          </h4>
          <p style="margin:-10px 0px;"><small>Author : {{ item.author }}</small></p>
          <p><small>Category : {{ item.category }}</small></p>
          <p class="card-text">
            {{ item.content | safe | truncatechars_html:30 }}
          </p>
          <a
            href="{% url 'myapp:post_detail' item.id %}"
            type="button"
            class="btn btn-light-blue btn-md"
          >
            もっと読む
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-6">
    <br />
    <h2>Login</h2>
    <br />

    <form action="" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
        {{field.label }}
        {{ field }}
        {{ field.errors }}
        <br />
      {% endfor %}

      <button type="submit" class="btn btn-primary">Login</button>
      <br />
      <br />
    </form>
  </div>
</div>

{% endblock %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-6">
    <br />
    <h2>Login</h2>
    <br />
    <p>ログアウトしました</p>
  </div>
</div>

{% endblock %}

myapp/templates/myapp/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-9">
    <br />
    <h2>Post削除</h2>
    <br />
    <div class="alert alert-danger" role="alert">
      <form method="post">
        {% csrf_token %}
        <p>以下の内容を本当に削除しますか？</p>
        <input type="submit" class="btn btn-danger" value="削除する" />
      </form>
    </div>
    <br />
    <p>タイトル</p>
    {{ object.title }}
    <hr />
    <p>内容</p>
    {{ object.content }}
    <br />
    <br />
  </div>
</div>

{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-9">
    <br />
    <!-- Card -->
    <div class="card">
      <!-- Card image -->
      {% if object.thumbnail %}
      <img
        class="card-img-top"
        src="{{ object.thumbnail.url }}"
        alt="{{ object.title }}"
      />
      {% else %}
      <img
        class="card-img-top"
        src="https://mdbootstrap.com/img/new/standard/nature/184.jpg"
        alt="{{ object.title }}"
      />
      {% endif %}

      <!-- Card content -->
      <div class="card-body">
        <!-- Title -->
        <h5 class="card-title"><a>{{ object.title }}</a></h5>
        <!-- Text -->
        <p class="card-text">
          {{ object.content | safe | linebreaksbr | urlize }}
        </p>
        <!-- Button -->
        <a
          class="btn"
          href="{% url 'myapp:like_add' object.pk %}"
          style="background-color: #ff6699; color: white"
          >お気に入りにいれる</a
        >
        <hr />
        <a
          href="javascript:void(0);"
          onclick="window.history.back();"
          class="btn btn-outline-dark"
          >戻る</a
        >
        {% if object.author == request.user %}
        <a
          href="{% url 'myapp:post_update' object.pk %}"
          class="btn btn-primary"
          >更新</a
        >

        <a href="{% url 'myapp:post_delete' object.pk %}" class="btn btn-danger"
          >削除</a
        >
        {% endif %}
      </div>
    </div>
    <br />
  </div>
  <div class="col-md-3">
    <br />
    <!-- Card -->
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ object.category }}</h5>
        <p>このカテゴリの他の記事</p>
      </div>
      <ul class="list-group">
        {% for item in category_posts %}
        <li class="list-group-item">
          <a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
    <!-- Card -->
  </div>
</div>
{% endblock %}

myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-9">
    <br />
    <h2>Post登録・更新</h2>
    <br />

    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label>タイトル</label>
        {{ form.title }}
      </div>

      <div class="form-group">
        <label>カテゴリ</label>
        {{ form.category }}
      </div>

      <div class="form-group">
        <label>サムネイル画像</label>
        {{ form.thumbnail }}
      </div>

      <br />
      <div class="form-group">
        <label>内容</label>
        　{{ form.content }}
      </div>
      <br />
      <button type="submit" class="btn btn-primary">保存</button>
    </form>
  </div>
</div>

{% endblock %}

myapp/templates/myapp/post_list.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-9">
    <br />
    <h2>Post一覧</h2>
    <br />
    <table class="table">
      <thead>
        <tr>
          <th width="200px">タイトル</th>
          <th>内容</th>
          <th width="200px">作成日時<br />更新日時</th>
        </tr>
      </thead>
      <tbody>
        {% for item in post_list %}
        <tr>
          <td>
            <a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a>
          </td>
          <td>{{ item.content | safe | truncatechars_html:30 }}</td>
          <td>
            {{ item.created_at.date }}
            <br />
            {{ item.updated_at.date }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
    {% include 'myapp/pagination.html' %}

    <br />
  </div>
</div>

{% endblock %}

myapp/templates/myapp/search.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-9">
    <br />
    <h2>Post一覧</h2>
    <br />
    <table class="table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>内容</th>
          <th>作成日時</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <tbody>
        {% for item in search_list %}
        <tr>
          <td>
            <a href="{% url 'myapp:post_detail' item.pk %}">{{ item.title }}</a>
          </td>
          <td>{{ item.content }}</td>
          <td>{{ item.created_at }}</td>
          <td>{{ item.updated_at }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
  </div>
</div>

{% endblock %}

myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %} {% block content %}

<div class="row">
  <div class="col-md-6">
    <br />
    <h2>Signup</h2>
    <br />

    <form action="" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
        {{field.label }}
        {{ field }}
        {{ field.errors }}
        <br />
      {% endfor %}

      <button type="submit" class="btn btn-primary">SignUp</button>
      <br />
      <br />
    </form>
  </div>
</div>

{% endblock %}